version: '3'
services:
  nginx:
    build:
      context: '.'
      dockerfile: 'nginx/Dockerfile'
    depends_on:
    - app
    network_mode: 'service:app'
  app:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:80' 
    environment:
      AWS_PROFILE: "vtypeio"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
